//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Store.PartnerCenter.Bot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Store.PartnerCenter.Bot.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}! What would you like to do?.
        /// </summary>
        internal static string AuthenticationSuccessDoneMessage {
            get {
                return ResourceManager.GetString("AuthenticationSuccessDoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer context is now configured to.
        /// </summary>
        internal static string CustomerContext {
            get {
                return ResourceManager.GetString("CustomerContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to unprotect the specified data..
        /// </summary>
        internal static string DataProtectionUnprotectException {
            get {
                return ResourceManager.GetString("DataProtectionUnprotectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can interact with me in the following ways:.
        /// </summary>
        internal static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication request was invalid. Try authenticating again if the issue persist please contact support..
        /// </summary>
        internal static string InvalidAuthenticationException {
            get {
                return ResourceManager.GetString("InvalidAuthenticationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a customer before attempting this operation. Please type ** list customers **, select a customer, and then try again..
        /// </summary>
        internal static string InvalidCustomerContextException {
            get {
                return ResourceManager.GetString("InvalidCustomerContextException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list customers.
        /// </summary>
        internal static string ListCustomersHelpMessage {
            get {
                return ResourceManager.GetString("ListCustomersHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        internal static string ListOperation {
            get {
                return ResourceManager.GetString("ListOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscriptions.
        /// </summary>
        internal static string ListSubscriptionssHelpMessage {
            get {
                return ResourceManager.GetString("ListSubscriptionssHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginCaptial {
            get {
                return ResourceManager.GetString("LoginCaptial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account you authenticated with is not associated with a tenant that has a relationship with the reseller. Please contact support for further assistances..
        /// </summary>
        internal static string NoRelationshipException {
            get {
                return ResourceManager.GetString("NoRelationshipException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first login before interacting with me. Please type ** login ** to authenticate. If you still need help type ** help ** after successfully authenticating..
        /// </summary>
        internal static string NotAuthenticatedHelpMessage {
            get {
                return ResourceManager.GetString("NotAuthenticatedHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the specified instance..
        /// </summary>
        internal static string RedisCacheConnectionException {
            get {
                return ResourceManager.GetString("RedisCacheConnectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reword your question and try again..
        /// </summary>
        internal static string RewordQuestion {
            get {
                return ResourceManager.GetString("RewordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SelectCaptial {
            get {
                return ResourceManager.GetString("SelectCaptial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot invoke this function after the bot service has been initialized..
        /// </summary>
        internal static string ServiceInitializedException {
            get {
                return ResourceManager.GetString("ServiceInitializedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click the button below to login..
        /// </summary>
        internal static string SigninCardText {
            get {
                return ResourceManager.GetString("SigninCardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription context is now configured to.
        /// </summary>
        internal static string SubscriptionContext {
            get {
                return ResourceManager.GetString("SubscriptionContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the subscriptions for {0}.
        /// </summary>
        internal static string SubscriptionRequestMessage {
            get {
                return ResourceManager.GetString("SubscriptionRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully authenticated! Please feel free to close this window and continue talking with the bot..
        /// </summary>
        internal static string SuccessfulAuthentication {
            get {
                return ResourceManager.GetString("SuccessfulAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the selected customer. Please type ** list customers ** and try again..
        /// </summary>
        internal static string UnableToLocateCustomer {
            get {
                return ResourceManager.GetString("UnableToLocateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the selected subscription. Please type ** list subscriptions ** and try again..
        /// </summary>
        internal static string UnableToLocateSubscription {
            get {
                return ResourceManager.GetString("UnableToLocateSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Partner Center Bot. You must first login before interacting with me. Please type ** login ** to authenticate. If you still need help type ** help ** after successfully authenticating..
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
